name: Run Tests

# Trigger the workflow on push or pull request events to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up GCC (G++) for C++ compilation
    - name: Set up GCC
      run: sudo apt-get install g++ make

    # Step 3: Install dependencies (if any, such as Catch2 if not header-only)
    # If you need Catch2 installed, you can add that here
    # For example, to install Catch2 via apt:
    # - name: Install Catch2
    #   run: sudo apt-get install libcatch2-dev

    # Step 4: Set up the build and run tests
    - name: Build and run tests
      run: |
        make test  # Build the project
        make run_tests  # Run the tests

    # Step 5: Save test results (optional, if you want to persist test output)
    # You could use GitHub Actions artifacts or logs for test outp
