name: Run Tests

# Trigger the workflow on push or pull request events to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Install GCC, make, and any other dependencies
    - name: Install GCC, make, and Catch2 (if needed)
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ make libcatch2-dev  # Install GCC, make, and Catch2

    # Step 3: Build the project and run tests
    - name: Build and run tests
      run: |
        make all  # Build the project (including the main program)
        make run_tests  # Run the tests

    # Optional: Save test results (if you want to persist logs or outputs)
    # - name: Upload test results
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: test-results
    #     path: ./test-results.log
