name: Run Tests

# Trigger the workflow on push or pull request events to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Install GCC and make
    - name: Install GCC and make
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ make  # Only install GCC and make, no need for Catch2

    # Step 3: Build the project and run tests
    - name: Build and run tests
      run: |
        make clean  # Clean previous builds
        make all  # Build the project (including the main program)
        make run_tests  # Run the tests
